# build environment
FROM node:14-alpine as Wbuild

WORKDIR /app

COPY . .

RUN npm install

RUN npm build

# production environment
FROM nginx:stable-alpine

COPY ./nginx.conf ./etc/nginx/conf.d/default.conf

COPY --from=Wbuild ./ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]