version: "3.9" # optional since v1.27.0
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_mydata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: iamtheuser
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
volumes:
  mysql_mydata:
